name: 'Artifact Upload'
description: 'Artifact Upload using Backblaze as the backend'
author: 'Rojan Gh.'
inputs:
  name:
    required: true
    description: 'Artifact name'
  path:
    required: false
    description: 'Path to the contents to be uploaded'
    default: './'
  key:
    required: true
    description: 'Backblaze application key'
  id:
    required: true
    description: 'Backblaze application key id'
  bucket:
    required: false
    description: 'Backblaze bucket name'
    default: 'github-artifacts'
runs:
  using: 'node16'
  main: 'dist/index.js'
